apiVersion: v1
kind: Pod
metadata:
  name: redis
  namespace: dbplatform
  labels:
    app: redis
spec:
  containers:
    - name: redis
      image: "redis:latest"
      ports:
        - containerPort: 6379
          hostPort: 16279
