apiVersion: v1
kind: Pod
metadata:
  name: pod1
  namespace: namespace1
spec:
  tolerations:
    - key: "node-role.kubernetes.io/control-plane"
      operator: "Exists"
      effect: "NoSchedule"
    - key: "node.kubernetes.io/disk-pressure"
      operator: "Exists"
      effect: "NoSchedule"
  containers:
    - name: alpine
      image: "alpine:latest"
      command: ["/bin/sleep", "3650d"]
      ports:
        - containerPort: 50055
          hostPort: 50055
      imagePullPolicy: IfNotPresent
