apiVersion: v1
kind: Pod
metadata:
  name: openuserinfo
  namespace: openplatform
spec:
  containers:
    - name: hellouserinfo
      image: "karldoenitz/hellouserinfo:1.4"
      ports:
        - containerPort: 50021
          hostPort: 50021
      env:
        - name: runport
          value: 50021
        - name: etcdiport
          valueFrom:
            configMapKeyRef:
              name: openplatform
              key: etcd-iport
      imagePullPolicy: IfNotPresent
