apiVersion: v1
kind: Pod
metadata:
  name: sshdserver
  namespace: openplatform
spec:
  containers:
    - name: centos
      image: "centos:7"
      command: ["/bin/sleep", "3650d"]
      securityContext: 
        privileged: true
      env:
        - name: etcdiport
          valueFrom:
            configMapKeyRef:
              name: openplatform
              key: etcd-iport
      imagePullPolicy: IfNotPresent
