apiVersion: v1
kind: Pod
metadata:
  name: testadd2container
  namespace: openplatform
spec:
  containers:
    - name: centos
      image: "centos:7"
      command: ["/bin/sleep", "3650d"]
      ports:
        - containerPort: 50055
          hostPort: 50055
      env:
        - name: etcdiport
          valueFrom:
            configMapKeyRef:
              name: openplatform
              key: etcd-iport
      imagePullPolicy: IfNotPresent
    - name: ubuntu
      image: "ubuntu:devel"
      command: ["/bin/sleep", "3650d"]
      ports:
        - containerPort: 50053
          hostPort: 50055
      env:
        - name: etcdiport
          valueFrom:
            configMapKeyRef:
              name: openplatform
              key: etcd-iport
      imagePullPolicy: IfNotPresent
