apiVersion: v1
kind: Pod
metadata:
  name: testadd2container
  namespace: openplatform
spec:
  containers:
    - name: centos
      image: "centos:7"
      imagePullPolicy: IfNotPresent
    - name: ubuntu
      image: "ubuntu:devel"
      imagePullPolicy: IfNotPresent
